all:
  children:
    testko_server_group:
        hosts:
          testko_server:
            ansible_host: testko.inservioserver.com
            ansible_port: 2222
            ansible_user: root
            ansible_python_interpreter: /usr/bin/python3
            #
            ispconfig_hostname: "testko.inservioserver.com"
            mail_admin_password: "123456"
            roundcube_admin_password: "123456"
            phpmyadmin_user_password: "123456"
            ispconfig_admin_password: "123456"
            ispconfig_mysql_root_password: "123456"
            ispconfig_mysql_ispconfig_password: "123456"
            ispconfig_mysql_master_root_password: "123456"
            mail_admin_email: "a2S"
            mail_base_domain: "testko.inservioserver.com"
            phpmyadmin_hostname: "testko.inservioserver.com"
            roundcube_hostname: "testko.inservioserver.com"
