---
- when: "install_and_upgrade_packages is true"
  block:
    - import_tasks: upgrade_packages.yml
      when: upgrade_packages is true

    - import_tasks: install_php_packages.yml

- import_tasks: autoinstall.yml
